const types = {
  REQUEST_LOGIN: 'REQUEST_LOGIN',
  SUCCESS_LOGIN: 'SUCCESS_LOGIN',
  FAIL_LOGIN: 'FAIL_LOGIN',
  LOGOUT: 'LOGOUT',
  LOGGED_OUT: 'LOGGED_OUT',
  CHECK_AUTHENTICATION: 'CHECK_AUTHENTICATION',
}

export default types
